extern const char *vertexShader;
extern const char *spherePixelShader;
extern const char *thickShader;
extern const char *thichPixelShader;
extern const char *colliderShader;
extern const char *colliderPixelShader;
extern const char *floorVS, *floorPS;
extern const char *mblurVS, *mblurGS, *particlePS;
extern const char *passThruVS, *texture2DPS;
extern const char *postprocessingPS;
